import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: "Gallery - My Next App",
	description: 'Generated by create next app',
}

export default function galleryLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div>{children}</div>
	)
}
