import Header from '@/components/Header'
import '../styles/globals.css'

export const metadata = {
	title: 'My Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">

			<body>

				<Header />

				<main className='mt-4    mx-auto lg:w-[1024px] px-4 lg:px-0'>
					{children}
				</main>
			</body>
		</html>
	)
}
